### ISSUE TITLE
CLIAR milestones

### ISSUE THREAD

**Issue by galileukim** [worldbank/institutional-assessment-dashboard#322]
- [x] summary of how data update was executed in 2024 (Ileana, Ify).
- [ ] reproducibility package (Ify).
- [x] sub-divide AFR into AFW and AFE (Ileana, Pinyi).
- [ ] ensure that the PowerPoint Button is working (@kannanv93)
- [x] include revised CLIAR figure in the automatic ppts and word (Kannan).
- [x] bivariate correlation, change the year from 2022 to 2023 (logged GDP).
- [x] add an advanced report button in the Country Benchmarking tab (Kannan).
- [x] create a data export button for the graph in the Bivariate Correlation tab (Kannan).
- [x] ensure that captions for the graphs are complete (Kannan).
- [ ] ensure that dynamic average data is correctly downloaded (@kannanv93 @ileanamarroquin ).

for next FY:
- [ ] inclusion of b-ready indicators (TBD).

**Comment by kannanv93** [comment]
Thanks Gali, Will update changes by Monday

**Comment by kannanv93** [comment]
Data export button for the graph - Complete

<img width="1026" alt="image" src="https://github.com/user-attachments/assets/f9e28509-f3fc-487f-b800-50f9df980443">

**Comment by kannanv93** [comment]
@galileukim < add an advanced report button in the Country Benchmarking tab (Kannan).> 
We currently have an option to select the tick box and download editable report, this will produce the advanced report. Do we still need a separate button ? 
<img width="336" alt="image" src="https://github.com/user-attachments/assets/de866d70-8c70-4702-9928-6890a9437b33">

**Comment by kannanv93** [comment]
@galileukim  : Regd. bivariate correlation, change the year from 2022 to 2023 (log GDP).  Is it a data change or just a change on UI ?

**Comment by ileanamarroquin** [comment]
> @galileukim : Regd. bivariate correlation, change the year from 2022 to 2023 (log GDP). Is it a data change or just a change on UI ?

@kannanv93: I'm following up this comment you mentioned @galileukim  because the footnote issue is more complex than just adding an if condition, I first want to make sure that the log GDP variable specification is the correct one. 

Here's an example with some issues to discuss:

1. **Footnote Content:** The footnote currently only displays the description of the independent variable (x-axis). Should we keep it this way? I've attached an image for reference:
   ![LOGGDP](https://github.com/user-attachments/assets/16ee5e45-cf61-433a-ace7-ae356f17280a)

2. **Outdated Footnote Description:** The footnote description is extracted from the `Description` variable in the `db_variables` file. However, for the specific case of the log GDP variable (`wdi_nygdppcapppkd`), the description is outdated. It currently states a base year of 2017, while in reality, the base year is 2021 (I've personally verified this). We should correct this description and potentially others in the `db_variables` file.

3. **Average of logGDP Variable:** According to the `\code\05-ctf.Rmd` script, there's a comment specifying a specific methodology that requires a 5-year average for the log GDP variable. Here are the relevant code lines:
   ![avgloggdp](https://github.com/user-attachments/assets/aec48735-a292-48e0-8b04-106f5a66a8c5)

My concern is twofold:

   a) Is this 5-year average exported as part of the `db_variables` file?
   b) Is this 5-year average used when generating the plot using the functions from the `auxiliary` functions in the `plots.R` script? Here's the relevant code snippet:
   ![correlationplot](https://github.com/user-attachments/assets/b5a1a6c2-6f46-4079-bf45-7f00646c7ae9)

Based on this code, it seems like the current plot might not be using an average and is potentially only considering the last year of observation. I could be wrong, but I'd like to confirm this with @kannanv93 who knows the app part better. If this is the case, we can eliminate this concern and implement the if condition in the function for users selecting the log GDP for the graph.

**Comment by kannanv93** [comment]
1. @ileanamarroquin Fixed the 1st issue. The note had info of both x and y axis but because of the margins, the note was getting cut. I have fixed this issue<img width="1224" alt="image" src="https://github.com/user-attachments/assets/ba3312c9-6c9c-4aed-87e4-60186ad514ce" />
2. Yes, changing the var_name and description in db_variables will solve this issue.
<img width="796" alt="image" src="https://github.com/user-attachments/assets/bb282817-dff8-478a-92b2-298ff67f9cc7" /> Also the reason why this discrepancy exists is because we had original WDI data which used 2017 and in October we shifted to new WDI data were 2021 was used. 
3. Yes, for GDP, our current process takes average across all other variables but for GDP, we had used year 2023. This code is also from 05-CTF- Line 150. I think we should remove this filter, not sure why this was the case at first place 
<img width="440" alt="image" src="https://github.com/user-attachments/assets/d8043a23-c206-4c50-82f8-1c48380da69b" />
